/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface:                    '#131313',
        'surface-dim':              '#131313',
        'surface-bright':           '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low':    '#1c1b1b',
        'surface-container':        '#201f1f',
        'surface-container-high':   '#2a2a2a',
        'surface-container-highest':'#353534',
        'surface-variant':          '#353534',
        'on-surface':               '#e5e2e1',
        'on-surface-variant':       '#c4c7c8',
        'on-background':            '#e5e2e1',
        background:                 '#131313',
        primary:                    '#ffffff',
        'on-primary':               '#2f3131',
        'primary-fixed':            '#e2e2e2',
        'primary-fixed-dim':        '#c6c6c7',
        'primary-container':        '#e2e2e2',
        'on-primary-container':     '#636565',
        'inverse-surface':          '#e5e2e1',
        'inverse-on-surface':       '#313030',
        'inverse-primary':          '#5d5f5f',
        secondary:                  '#c6c6cf',
        'secondary-container':      '#45464e',
        'secondary-fixed':          '#e2e1eb',
        'secondary-fixed-dim':      '#c6c6cf',
        'on-secondary':             '#2f3037',
        'on-secondary-container':   '#b4b4bd',
        tertiary:                   '#ffffff',
        'tertiary-container':       '#e2e2e2',
        'tertiary-fixed':           '#e2e2e2',
        'tertiary-fixed-dim':       '#c6c6c7',
        'on-tertiary':              '#2f3131',
        'on-tertiary-container':    '#636565',
        outline:                    '#8e9192',
        'outline-variant':          '#444748',
        error:                      '#ffb4ab',
        'error-container':          '#93000a',
        'on-error':                 '#690005',
        'on-error-container':       '#ffdad6',
        'surface-tint':             '#c6c6c7',

        // RepoRounder severity colours
        critical: '#EF4444',
        warning:  '#F59E0B',
        info:     '#3B82F6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
        'gutter':          '1rem',
        'gutter-desktop':  '1.5rem',
      },
      fontFamily: {
        sans:  ['Inter', 'sans-serif'],
        mono:  ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display':      ['36px', { lineHeight: '44px', letterSpacing: '-0.03em',  fontWeight: '600' }],
        'headline-lg':  ['24px', { lineHeight: '32px', letterSpacing: '-0.02em',  fontWeight: '600' }],
        'headline-md':  ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'headline-sm':  ['16px', { lineHeight: '24px', letterSpacing: '-0.01em',  fontWeight: '500' }],
        'body-lg':      ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md':      ['14px', { lineHeight: '20px', letterSpacing: '0em',      fontWeight: '400' }],
        'body-sm':      ['12px', { lineHeight: '18px', letterSpacing: '0.005em',  fontWeight: '400' }],
        'label-md':     ['12px', { lineHeight: '16px', letterSpacing: '0.01em',   fontWeight: '500' }],
        'label-sm':     ['11px', { lineHeight: '14px', letterSpacing: '0.04em',   fontWeight: '500' }],
        'code-lg':      ['14px', { lineHeight: '22px', letterSpacing: '0em',      fontWeight: '400' }],
        'code-md':      ['13px', { lineHeight: '20px', letterSpacing: '0em',      fontWeight: '400' }],
        'code-sm':      ['12px', { lineHeight: '18px', letterSpacing: '0em',      fontWeight: '400' }],
      },
      keyframes: {
        'pulse-dot': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.4' } },
      },
      animation: {
        'pulse-dot': 'pulse-dot 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
